name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Build
        run: npm run build

      - name: Copy index.html to 404.html
        run: cp dist/portfolio-thiago-duarte/index.html dist/portfolio-thiago-duarte/404.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/portfolio-thiago-duarte
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true

      - name: Verify Deployment
        run: |
          echo "Deployment completed! Your site should be available at:"
          echo "https://thiagorduarte1107.github.io/portfolio-thiago-duarte/"
          echo "Please allow a few minutes for the changes to propagate."
          echo "You can check the deployment status in the 'Actions' tab of your repository."